### ISSUE TITLE
how to use without composer? is it possible?

### ISSUE THREAD

**Issue by Mst1k** [tufanbarisyildirim/php-apk-parser#102]
i am interested in using this library in one of my projects, but i am unable to use composer, how can i proceed to install/include this inside my project?

**Comment by tufanbarisyildirim** [comment]
The complete library is in `/lib/ApkParser` folder and it is psr-0 compatible. 
So you can have your own autoloader to find any class inside that path and include. 
How do you do this for other libraries?

**Comment by Mst1k** [comment]
Thanks so much, i was able to make include it in the project, i did exactly that, setted up the autoload and, it worked very well!
