### ISSUE TITLE
Warning ApkResource.php

### ISSUE THREAD

**Issue by Jahak** [tufanbarisyildirim/php-apk-parser#28]
Hello, when opening a file ApkResource.php returns an error Warning: Invalid argument supplied for foreach() on line 9, what to do?

**Comment by shaharpan** [comment]
Facing same issue, can anyone help?

**Comment by shaharpan** [comment]
Sample APK I am trying is: https://s3.us-east-2.amazonaws.com/intricare-dev/123465789/1512566305/Flashlight+-+Torch.apk
