### ISSUE TITLE
Application Label(Name) and Icon not being Extracted in Some .apk files

### ISSUE THREAD

**Issue by abhinay1435** [tufanbarisyildirim/php-apk-parser#44]
I am using the Following Code to Extract Icon and Application Name from .apk file , but for some apk it is generating properly and for some it is not

(SHORTNAMES)
Working Apk === Good Apk
Not Working Apk == faulty APk

$resourceId = $apk->getManifest()->getApplication()->getIcon();
$resources = $apk->getResources($resourceId);

header('Content-type: text/html');
foreach ($resources as $resource) {
    echo '<img src="data:image/png;base64,', base64_encode(stream_get_contents($apk->getStream($resource))), '" />';
}

$labelResourceId = $apk->getManifest()->getApplication()->getLabel();
echo $labelResourceId;
$appLabel = $apk->getResources($labelResourceId);
echo "<br>Hello Application Name is :-";
echo $appLabel[0];

I just echo $labelResourceId;
and saw that Resource Id is being Generated for those faulty apk but resources are not being extracted for those
for Label it is giving null as return

and for Icon it is giving
Error ==stream_get_contents() expects parameter 1 to be resource

the faulty apk file is MainActivity.apk
which I have already mailed you sir

**Comment by shaharpan** [comment]
Anyone got solution to this?

**Comment by ajayqualwebs** [comment]
$manifest = $apk->getManifest();
$permissions = $manifest->getPermissions();
$appNameResourceId = $manifest->getApplication()->getLabel();
$appIconResourceId = $apk->getManifest()->getApplication()->getIcon();
$appName = $apk->getResources($appNameResourceId)[0];
$appIcon = $apk->getResources($appIconResourceId)[0];
this is my code, this is proper working for me. please may be it'll also helpful for you.
