### ISSUE TITLE
Using script without composer ?

### ISSUE THREAD

**Issue by adrianTNT** [tufanbarisyildirim/php-apk-parser#45]
Is it possible to use php-apk-parser without composer? 
I tried uploading the zip contents on server and ran /test/ParserTest.php but got this error:

```
Fatal error: Class 'PHPUnit_Framework_TestCase' not found in /test/ParserTest.php on line 14
```
Any way around this or is composer a must ?

**Comment by phudinsky** [comment]
How you run tests?

**Comment by tufanbarisyildirim** [comment]
/test/ folder is for unit testing, you can download phpunit to test.
please use /example learn see how to use.
