### ISSUE TITLE
How to use Remote URL of APK file instead of location in local folder?

### ISSUE THREAD

**Issue by MihirGosai** [tufanbarisyildirim/php-apk-parser#48]
In Archive.php , it accepts only file location of APK file like C:/APK/file.apk but not remote URL like www.example.com/file.apk
Can you please add support of remote URL path of APK?

**Comment by phpbeginners** [comment]
It isn't possible because the script needs to extract the contents in an APK file to read the manifest.xml file. Moreover, if you wish to use any remote URL, still the file will need to be copied to a local directory for further processing.

**Comment by MihirGosai** [comment]
Any way to get compatible-screens->screen values of android manifest file?

**Comment by tufanbarisyildirim** [comment]
Just use curl or file_get_contents to pull file on your server before you use apk-parser.
