### ISSUE TITLE
Invalid or uninitialized Zip object

### ISSUE THREAD

**Issue by iroben** [tufanbarisyildirim/php-apk-parser#60]
Warning: ZipArchive::getStream(): Invalid or uninitialized Zip object

 in vendor/tufanbarisyildirim/php-apk-parser/lib/ApkParser/Archive.php on line 65

APK has 50M, can not upload
APK download page: http://www.coolapk.com/apk/com.google.android.webview

**Comment by MihirGosai** [comment]
All google apps (gapps) updates throw this error nowadays..
Haven't find this problem with other apps till now.

**Comment by nickrobillard** [comment]
Not ideal but I've worked around this by using shell_exec to unzip and then re-zip the offending APK file. The new APK then works fine with this lib.

**Comment by smoqadam** [comment]
I had the same issue. Update your `zip` extension to latest version.

**Comment by shaharpan** [comment]
@smoqadam I am running on PHP 5.6.31 on Windows server, As the Ziparchive is bundled with this version, I am not sure how to update zip version. Is there any workaround?

**Comment by khaintt** [comment]
@smoqadam I had similar issue, updated zip to latest version but not help. I'm running PHP 7.0 on ubuntu server. And this issue happened with non-google apps also(Spotify) ~ more than 3Mb apk.
