### ISSUE TITLE
error when parsing google earth apk

### ISSUE THREAD

**Issue by devbysb** [tufanbarisyildirim/php-apk-parser#63]
Hi i have a error when i try to parse google earth apk

Fatal error: Uncaught exception 'Exception' with message 'Unrecognized tag code '100' at offset 6300' in /var/www/includes/ApkParser/XmlParser.php:189 Stack trace: #0 /var/www/includes/ApkParser/XmlParser.php(295): ApkParser\XmlParser->decompress() #1 /var/www/includes/ApkParser/XmlParser.php(310): ApkParser\XmlParser->getXmlString() #2 /var/www/includes/ApkParser/Manifest.php(152): ApkParser\XmlParser->getXmlObject('\ApkParser\Mani...') #3 /var/www/includes/ApkParser/Manifest.php(104): ApkParser\Manifest->getXmlObject() #4 /var/www/includes/ApkParser/Manifest.php(61): ApkParser\Manifest->getAttribute('package') #5 /var/www/includes/applications.class.php(66): ApkParser\Manifest->getPackageName() #6 /var/www/debug_apk.php(16): Applications->apkGetInformations('temp/98760/goog...') #7 {main} thrown in /var/www/includes/ApkParser/XmlParser.php on line 189

Could you help me please :)

**Comment by tufanbarisyildirim** [comment]
this should not be a case anymore, (even you should not have this apk, lol) feel free to re-open if you get same error.
