### ISSUE TITLE
Android studio 3.0 apks

### ISSUE THREAD

**Issue by Mutalistik** [tufanbarisyildirim/php-apk-parser#66]
Hello I'm getting an error using apkParser since I have update to android studio 3.0 It seems that something has change in the apk compiler, maybe the encoding o something like that. The error is 

ErrorException in XmlParser.php line 244:
Undefined offset: 4476

I looked the function and its trying to get a position greater of the array length
I tried with other versions of the same apk compiled with older android studio versions and it works

I make a test apk for you to test it 
[app-debug.apk.zip](https://github.com/tufanbarisyildirim/php-apk-parser/files/1488826/app-debug.apk.zip)

Regards

**Comment by achretien** [comment]
can you test since https://github.com/tufanbarisyildirim/php-apk-parser/commit/4d23e0f87b7e2db77b7f9d7d69f9da08a22b9e1c ?

**Comment by ronzyfonzy** [comment]
Have the same problem after building with AndroidStudio 3.0. Tested out 4d23e0f and I'm getting 
```
Unrecognized tag code '0' at offset 10400
```

**Comment by peterchaula** [comment]
@achretien 4d23e0f fixed the issue for me

**Comment by WebSabaki** [comment]
Hello. I face similar issues:

Unrecognized tag code '0' at offset 10400
or
 Unrecognized tag code '100' at offset 10288

**Comment by Mutalistik** [comment]
In my case all works well with the last versión.

**Comment by ronzyfonzy** [comment]
Tested again (with the 4d23e0f) and still getting error:
```
Fatal error: Uncaught exception 'Exception' with message 'Unrecognized tag code '0' at offset 9436' in /vendor/tufanbarisyildirim/p
hp-apk-parser/lib/ApkParser/XmlParser.php:194
Stack trace:
#0 /vendor/tufanbarisyildirim/php-apk-parser/lib/ApkParser/XmlParser.php(330): ApkParser\XmlParser->decompress()
#1 /vendor/tufanbarisyildirim/php-apk-parser/lib/ApkParser/XmlParser.php(345): ApkParser\XmlParser->getXmlString()
#2 /vendor/tufanbarisyildirim/php-apk-parser/lib/ApkParser/Manifest.php(156): ApkParser\XmlParser->getXmlObject('\\ApkParser\\Mani.
..')
#3 /vendor/tufanbarisyildirim/php-apk-parser/lib/ApkParser/Manifest.php(108): ApkParser\Manifest->getXmlObject()
#4 /vendor/tufanbarisyildirim/php-apk-parser/lib/ApkParser/Manifest.php(74): ApkParser\Manifest->getAttribute('versionName')
#5 /v in /vendor/tufanbarisyildirim/php-apk-parser/lib/ApkParser/XmlParser.php on line 194
```

I ran this code:
```php
try{
   $apk = new \ApkParser\Parser($apk_path);
} catch(Exception $e){
   print_r($e);
}
```

**Comment by bealebe** [comment]
Just wanted to share how I resolved this. 

The AndroidManifest.xml actually had a syntax error in it. The APK still would build and run on a device, but would break here when uploading because the XML syntax was bad.

Hopefully this will help someone!

**Comment by GustavoEmmel** [comment]
> Just wanted to share how I resolved this.
> 
> The AndroidManifest.xml actually had a syntax error in it. The APK still would build and run on a device, but would break here when uploading because the XML syntax was bad.
> 
> Hopefully this will help someone!

the same happens to me, there was a lost [ on manifest.
Apk still building and running, but show to error above when parsing.
