### ISSUE TITLE
Flexible parsing

### ISSUE THREAD

**Issue by WebSabaki** [tufanbarisyildirim/php-apk-parser#68]
Good afternoon. 

Would it be possible to get a flexible manifest parsing.

For instance

a.  `<manifest versionCode="0x14" versionName="1.0.20" package="XXX" versionCode="20" versionName="1.0.20" platformBuildVersionCode="23" platformBuildVersionName="6.0-2704002">`

duplicate versionCode and  version name but package found for instance on apkpure 

b. ` <meta-data name="du_keys" value="{"lockscreen":[{"pid":"14395"}],"list":[],"native":[{"pid":"10569"},{"pid":"10570"}]}">`

seems to be parsed okay (on apkpure) but failed at  value="{" . 

> Fatal Error 65: attributes construct error Line: 126 Column: 40 ----------------------------------------^ Fatal Error 73: Couldn't find end of Start Tag meta-data line 126 Line: 126 Column: 40 -----------------^

**Comment by tufanbarisyildirim** [comment]
This does not look like valid attrivute value (unescaped quotes etc) does that work on android? Can I have an example APK? @WebSabaki

**Comment by tufanbarisyildirim** [comment]
We may have exception for JSON values and parse until json end. That could be the only case we accept and invalid XML. PR appreciated.

**Comment by tufanbarisyildirim** [comment]
I think #100  solves it @WebSabaki
