### ISSUE TITLE
Error 500 with IIS and large apk (Chrome 72)

### ISSUE THREAD

**Issue by yurik94** [tufanbarisyildirim/php-apk-parser#73]
I got error 500 with no specified stacktrace when I read a 120 MB apk

**Comment by rehmatworks** [comment]
What's the `memory_limit`? Sounds to be an issue related to insufficient memory allocation considering that you are reading a larger file. The `memory_limit` should be higher than the APK file size.

**Comment by yurik94** [comment]
It's a VPS with 8GB of total RAM and I set the php script limit to 512MB...
I will investigate again

Il giorno dom 10 feb 2019, 19:59 Rehmat Alam <notifications@github.com> ha
scritto:

**Comment by tufanbarisyildirim** [comment]
It seems like a php configuration issue.
