### ISSUE TITLE
ZipArchive::getStream(): Invalid or uninitialized Zip object

### ISSUE THREAD

**Issue by tangzhangcheng** [tufanbarisyildirim/php-apk-parser#77]
When I use it in centos7.2 php5.6 and nginx environment, I will encounter a few apk package open failures. Program error (ZipArchive::getStream(): Invalid or uninitialized Zip object)

**Comment by tufanbarisyildirim** [comment]
This seems an invalid package - please re-open if you are sure thats a valid apk and apk-parser can not open it.
