### ISSUE TITLE
This repo depends on java environment. I found one way, faster, high performance! Cool!

### ISSUE THREAD

**Issue by PaulCnth** [tufanbarisyildirim/php-apk-parser#82]
You can see it here. It uses the PHP ZipArchive package, and parse the AndroidManifest.xml binary file. It works so fine, I use it for yeays.
One class solves your problem, amazing.

Look it here
[https://github.com/PaulCnth/myutility/blob/master/php/apk_parser.php](https://github.com/PaulCnth/myutility/blob/master/php/apk_parser.php)

**Comment by tufanbarisyildirim** [comment]
Java part which decompiles Dexes can be disabled by config
